### ISSUE TITLE
Make Hitchtroopers compatible with CTLD

### ISSUE THREAD

**Issue by HappyGnome** [HappyGnome/DCS_Scripts#2]

**Comment by HappyGnome** [comment]
https://forum.dcs.world/topic/120045-complete-transport-and-logistics-deployment-ctld

**Comment by techdr1ve** [comment]
Yea so honestly it's all about naming here all you'd have to do is make sure your naming for CTLD groups is the same as your hitchtroopers

**Comment by techdr1ve** [comment]
The more I think about this, I think combining this into CTLD is a bad idea, I'm sorry for recommending this.
You have enough to make this standalone without it.
