### ISSUE TITLE
Steersman - Zigzag Option Request

### ISSUE THREAD

**Issue by techdr1ve** [HappyGnome/DCS_Scripts#7]
Please include an option to enable zigzag feature of the steersman.lua script, some people would choose not to have that functionality. In our case we would like to simply turn that part off, preferably as an option hardcoded in the script and not the comms menu would be best from our POV! Great work, great scripts thank you so much for your hard work!

**Comment by HappyGnome** [comment]
Hi, thanks for this suggestion. I'll try to put this into an update soon. Note that the boats should not zigzag when players are near, it's just so that they don't have so far to turn when they switch modes.

**Comment by techdr1ve** [comment]
Oh I didn't even know that! If that's the case that they don't do this when players are near ... then this is NOT an issue and you can close it.
The request would change then to explain this specifically in the Readme that it doesn't zigzag when players are near, maybe just a note. Thanks!

Question, does it do it when AI is near or landing as well?
If so I would include if friendly AI planes are near or aboard the ship readying to launch not to do it if it's not too difficult to implement.

**Comment by HappyGnome** [comment]
I realised that you're probably using the comms menu controlled version, in which case it might still zigzag. Apologies for the confusion. Maybe I could make it so that for manual mode the default is not to zigzag.

The behaviour does not include AI, I'll have a think about that. If I fix the zigzagging for comms-menu mode, does the AI issue still need changes?

**Comment by HappyGnome** [comment]
I've just finished adding a new disableZigZag method and also making zig-zagging disabled by default for groups with comms menu control. This is on the Latest tag now.
