### ISSUE TITLE
Steersman - Option to Stop/Start Ship Movement from F10 Menu

### ISSUE THREAD

**Issue by techdr1ve** [HappyGnome/DCS_Scripts#9]
Getting Steersman - Option to Stop/Start Ship Movement from F10 Menu would be wonderful.
Reason is there are times for example where I want to place the Tarawa in a certain spot and have these AI helos take off from this intended spot. This flexibility in controlling the ship would be great.

**Comment by HappyGnome** [comment]
This should be possible. It might be a few weeks before I can get to this though. Thanks!

**Comment by techdr1ve** [comment]
Thanks so much!

**Comment by HappyGnome** [comment]
I've added the options to start/stop the AI of manually controlled Steersman groups via the F10 menu. This is on the Latest tag now. Let me know if you find any problems!

**Comment by techdr1ve** [comment]
Awesome ill check it out when i get a chance

**Comment by techdr1ve** [comment]
Works well, I did extensive testing a while back. My job changed and I had to can my project for a while. Hopefully be back into DCS mod coding in the future and server uptime. THanks so much for your work!
